spring.application.name=To-Do_List_Back

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/to_do_list
spring.datasource.username=postgres
spring.datasource.password=Dabson12
spring.datasource.driver-class-name=org.postgresql.Driver